//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wasm.Sdk.Analyzer.Proxy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wasm.Sdk.Analyzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //--------------------------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by Wasm.SDK.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////--------------------------------------------------------------------------------------------------
        ///
        ///{{ for using in Usings ~}}
        ///using {{ using }};
        ///{{ end ~}}
        ///
        ///namespace {{Class.Namespace}}
        ///{
        ///    public seal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSharpProxyTemplate {
            get {
                return ResourceManager.GetString("CSharpProxyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //--------------------------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by Wasm.SDK.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////--------------------------------------------------------------------------------------------------
        ///
        ///{{~ for export in DefaultExports ~}}
        ///export { default as {{ export }} } from &apos;./{{ export }}&apos;;
        ///{{~ end ~}}
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TypeScriptIndexTemplate {
            get {
                return ResourceManager.GetString("TypeScriptIndexTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //--------------------------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by Wasm.SDK.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////--------------------------------------------------------------------------------------------------
        ///
        ///{{~ for interface in Interfaces ~}}
        ///export interface {{ interface.Name }} {
        ///  {{~ for property in interface.P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TypeScriptInterfaceTemplate {
            get {
                return ResourceManager.GetString("TypeScriptInterfaceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //--------------------------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by Wasm.SDK.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////--------------------------------------------------------------------------------------------------
        ///
        ///import { getMethodInfo, invokeMethod, IWasmResource, WasmHelper } from &quot;./wasmShared&quot;
        ///{{ for tsImport in Impor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TypeScriptProxyTemplate {
            get {
                return ResourceManager.GetString("TypeScriptProxyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //--------------------------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by Wasm.SDK.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////--------------------------------------------------------------------------------------------------
        ///
        ///{{ for tsImport in Imports ~}}
        ///import { {{ tsImport.Types | array.join &quot;, &quot; }} } from &quot;./{{ tsImport.File }}&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TypeScriptProxyWorkerProxyTemplate {
            get {
                return ResourceManager.GetString("TypeScriptProxyWorkerProxyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //--------------------------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by Wasm.SDK.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////--------------------------------------------------------------------------------------------------
        ///
        ///{{ for tsImport in Imports ~}}
        ///import { {{ tsImport.Types | array.join &quot;, &quot; }} } from &quot;./{{ tsImport.File }}&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TypeScriptProxyWorkerTemplate {
            get {
                return ResourceManager.GetString("TypeScriptProxyWorkerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare global {
        ///    var BINDING: any;
        ///}
        ///
        ///export function invokeMethod(fqn: number, thisArg: number, signature: string, args: any[]): any {
        ///    let instancePtr = 0;
        ///    if (thisArg) {
        ///        // Get class instance Ptr from gcHandle
        ///        instancePtr = BINDING.wasm_get_raw_obj(thisArg);
        ///
        ///        // Make sure it hasn&apos;t been disposed.
        ///        if (!instancePtr) {
        ///            throw &quot;CalculatorController has been disposed. Attempted to call method on a GCed instance&quot;;
        ///        }
        ///    }
        ///
        ///    return [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wasmShared {
            get {
                return ResourceManager.GetString("wasmShared", resourceCulture);
            }
        }
    }
}
